import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import "@/app/globals.css"
import { ModalProvider } from "@/providers/modal-provider";
import { ToastProvider } from "@/providers/toast-provider";
import { SessionProvider } from "next-auth/react";
import { Footer } from "@/components/front-end/footer";
import NavbarComponent from "@/components/front-end/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>

    <html lang="en">

      <body className={inter.className}>
        
<ToastProvider/>
        <ModalProvider/>
        <NavbarComponent>
          
        </NavbarComponent>
        {children}
        <Footer></Footer>
        </body>
    </html>
    </SessionProvider>

  );
}
